export const GOOGLE_ARABIC_FONTS = [
    { name: 'Cairo', label: 'Cairo (القاهرة)' },
    { name: 'Tajawal', label: 'Tajawal (تجوّل)' },
    { name: 'Almarai', label: 'Almarai (المراعي)' },
    { name: 'El Messiri', label: 'El Messiri (المصيري)' },
    { name: 'Rubik', label: 'Rubik (روبيك)' },
    { name: 'IBM Plex Sans Arabic', label: 'IBM Plex Sans Arabic (الأساسي)' },
    { name: 'Noto Kufi Arabic', label: 'Noto Kufi Arabic (نوتو كوفي)' },
    { name: 'Noto Sans Arabic', label: 'Noto Sans Arabic (نوتو نسخ)' },
    { name: 'Alexandria', label: 'Alexandria (الإسكندرية)' },
    { name: 'Marhey', label: 'Marhey (مرحي)' },
    { name: 'Rakkas', label: 'Rakkas (رقّاص)' },
    { name: 'Readex Pro', label: 'Readex Pro (ريدككس)' },
    { name: 'Mada', label: 'Mada (مدى)' },
    { name: 'Lateef', label: 'Lateef (لطيف)' },
    { name: 'Harmattan', label: 'Harmattan (حرمل)' },
    { name: 'Amiri', label: 'Amiri (أميري)' },
    { name: 'Aref Ruqaa', label: 'Aref Ruqaa (عارف رقعة)' },
    { name: 'Changa', label: 'Changa (تشانغا)' },
    { name: 'Lalezar', label: 'Lalezar (لاليزار)' },
    { name: 'Reem Kufi', label: 'Reem Kufi (ريم كوفي)' },
];
